import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#f976ba',
        secondary: '#006382',
        tertiary: '#a02d70',
        'on-primary-fixed': '#00121e',
        'secondary-fixed': '#93dbff',
        'on-secondary': '#e5f5ff',
        'tertiary-dim': '#912063',
        'surface-bright': '#f3f7ff',
        'primary-container': '#34b5fa',
        'error-dim': '#9f0519',
        'on-secondary-fixed': '#00394c',
        'primary-dim': '#00557b',
        error: '#b31b25',
        'surface-container': '#daeaff',
        'on-background': '#0c314e',
        'tertiary-container': '#ff8bc5',
        'on-secondary-container': '#004d67',
        'primary-fixed': '#34b5fa',
        'primary-fixed-dim': '#17a8ec',
        'on-surface': '#0c314e',
        'on-tertiary-fixed-variant': '#73004b',
        'on-tertiary': '#ffeff3',
        'inverse-primary': '#34b5fa',
        surface: '#f3f7ff',
        'surface-dim': '#b5d8ff',
        'error-container': '#fb5151',
        background: '#f3f7ff',
        'outline-variant': '#91b0d3',
        'surface-container-highest': '#c5dfff',
        'inverse-surface': '#000f1f',
        'on-tertiary-container': '#630040',
        'on-primary': '#e9f4ff',
        'secondary-dim': '#005672',
        'inverse-on-surface': '#81a0c2',
        'surface-container-low': '#e9f1ff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#003954',
        'on-surface-variant': '#3f5e7d',
        'secondary-container': '#93dbff',
        'on-error-container': '#570008',
        'on-secondary-fixed-variant': '#005773',
        primary: '#00628c',
        'on-error': '#ffefee',
        'surface-container-high': '#cfe5ff',
        'on-tertiary-fixed': '#360021',
        'tertiary-fixed': '#ff8bc5',
        'on-primary-container': '#003047',
        outline: '#5b799a',
        'surface-tint': '#00628c',
        'secondary-fixed-dim': '#78cef7',
        'surface-variant': '#c5dfff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'Noto Sans SC'],
        body: ['Plus Jakarta Sans', 'Noto Sans SC'],
        label: ['Plus Jakarta Sans', 'Noto Sans SC'],
      },
    },
  },
  plugins: [typography],
}

